/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project.weicheng.yuan;

import javafx.application.Application;

/**
 * Entry point class for the game application.
 * <p>
 * This class serves as the starting point for the JavaFX-based game application.
 * It primarily forwards the launch request to the main JavaFX application class, {@code FxMain}.
 */
@Generated
public class App {

    /**
     * Provides a greeting message, typically used for testing or initialization purposes.
     *
     * @return a greeting message.
     */
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * The main method, which serves as the entry point for the game application.
     *
     * @param args command-line arguments passed to the application.
     */
    public static void main(String[] args) {
        Application.launch(FxMain.class);
    }
}
